{
 "title": "Homework",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Load, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - avg without(cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) *100",
     "legendFormat": "CPU load, %"
    }
   ]
  },
  {
   "title": "Load Average, 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "LA1" },
    { "expr": "node_load5", "legendFormat": "LA5" },
    { "expr": "node_load15", "legendFormat": "LA15" }
   ]
  },
  {
   "title": "Free Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  {
   "title": "Free Space, /",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint='/'}"
    }
   ]
  }
 ]
}